// background_images.h
// NDS background images
// This file was automatically generated by Spritely 

#ifndef _BACKGROUND_IMAGES_H_
#define _BACKGROUND_IMAGES_H_

// Structure to store basic information for each background image
typedef struct {
	// Width/height for this image.
	short int width, height;
	
	const unsigned short int *data;
} BgImageInfoStruct;

// These palette/image data arrays are defined in background_images.cpp

// General info about each background image.
extern const BgImageInfoStruct BgImageInfo[];

// Number of background images.
const int kNumBgImages = 1;

// Background Image IDs
const int kBgImage_background_png = 0;

#endif	// _BACKGROUNDS_H_
